-- Additive verified seed. Safe after 001 + 002.
SET NAMES utf8mb4;

INSERT INTO concepts (id, slug, gloss_en) VALUES
  (5, 'potato', 'potato'),
  (6, 'football', 'association football'),
  (7, 'thousand', 'one thousand'),
  (8, 'factory', 'factory'),
  (9, 'theatre', 'theatre'),
  (10, 'music', 'music'),
  (11, 'lead-by-nose', 'to deceive someone by leading them along'),
  (12, 'pearls-before-swine', 'to offer something valuable to someone who cannot use it'),
  (13, 'digs-a-pit', 'harm intended for another returns to the doer'),
  (14, 'hold-tongue', 'to remain silent'),
  (15, 'cat-in-bag', 'to buy something without inspecting it'),
  (16, 'bird-in-hand', 'a sure small gain beats an uncertain larger one')
ON DUPLICATE KEY UPDATE gloss_en = VALUES(gloss_en);

INSERT INTO words (id, language_id, concept_id, lemma, display_form, normalized, slug, script, pos, is_phrase, register_tag) VALUES
  (30, 1, 5, 'krompir', 'krompir', 'krompir', 'krompir', 'Latn', 'noun', 0, NULL),
  (31, 2, 5, 'krumpir', 'krumpir', 'krumpir', 'krumpir', 'Latn', 'noun', 0, NULL),
  (32, 3, 5, 'krompir', 'krompir', 'krompir', 'krompir', 'Latn', 'noun', 0, NULL),
  (33, 4, 5, 'krompir', 'krompir', 'krompir', 'krompir', 'Latn', 'noun', 0, NULL),
  (34, 5, 5, 'krompir', 'krompir', 'krompir', 'krompir', 'Latn', 'noun', 0, NULL),
  (35, 6, 5, 'компир', 'компир', 'компир', 'kompir', 'Cyrl', 'noun', 0, NULL),
  (36, 7, 5, 'potato', 'potato', 'potato', 'potato', 'Latn', 'noun', 0, NULL),
  (37, 1, 6, 'fudbal', 'fudbal', 'fudbal', 'fudbal', 'Latn', 'noun', 0, NULL),
  (38, 2, 6, 'nogomet', 'nogomet', 'nogomet', 'nogomet', 'Latn', 'noun', 0, NULL),
  (39, 3, 6, 'fudbal', 'fudbal', 'fudbal', 'fudbal', 'Latn', 'noun', 0, NULL),
  (40, 3, 6, 'nogomet', 'nogomet', 'nogomet', 'nogomet', 'Latn', 'noun', 0, NULL),
  (41, 4, 6, 'fudbal', 'fudbal', 'fudbal', 'fudbal', 'Latn', 'noun', 0, NULL),
  (42, 5, 6, 'nogomet', 'nogomet', 'nogomet', 'nogomet', 'Latn', 'noun', 0, NULL),
  (43, 6, 6, 'фудбал', 'фудбал', 'фудбал', 'fudbal', 'Cyrl', 'noun', 0, NULL),
  (44, 7, 6, 'football', 'football', 'football', 'football', 'Latn', 'noun', 0, NULL),
  (45, 1, 7, 'hiljada', 'hiljada', 'hiljada', 'hiljada', 'Latn', 'noun', 0, NULL),
  (46, 2, 7, 'tisuća', 'tisuća', 'tisuca', 'tisuca', 'Latn', 'noun', 0, NULL),
  (47, 3, 7, 'hiljada', 'hiljada', 'hiljada', 'hiljada', 'Latn', 'noun', 0, NULL),
  (48, 4, 7, 'hiljada', 'hiljada', 'hiljada', 'hiljada', 'Latn', 'noun', 0, NULL),
  (49, 5, 7, 'tisoč', 'tisoč', 'tisoc', 'tisoc', 'Latn', 'noun', 0, NULL),
  (50, 6, 7, 'илјада', 'илјада', 'илјада', 'iljada', 'Cyrl', 'noun', 0, NULL),
  (51, 7, 7, 'thousand', 'thousand', 'thousand', 'thousand', 'Latn', 'noun', 0, NULL),
  (52, 1, 8, 'fabrika', 'fabrika', 'fabrika', 'fabrika', 'Latn', 'noun', 0, NULL),
  (53, 2, 8, 'tvornica', 'tvornica', 'tvornica', 'tvornica', 'Latn', 'noun', 0, NULL),
  (54, 3, 8, 'fabrika', 'fabrika', 'fabrika', 'fabrika', 'Latn', 'noun', 0, NULL),
  (55, 4, 8, 'fabrika', 'fabrika', 'fabrika', 'fabrika', 'Latn', 'noun', 0, NULL),
  (56, 5, 8, 'tovarna', 'tovarna', 'tovarna', 'tovarna', 'Latn', 'noun', 0, NULL),
  (57, 6, 8, 'фабрика', 'фабрика', 'фабрика', 'fabrika', 'Cyrl', 'noun', 0, NULL),
  (58, 7, 8, 'factory', 'factory', 'factory', 'factory', 'Latn', 'noun', 0, NULL),
  (59, 1, 9, 'pozorište', 'pozorište', 'pozoriste', 'pozoriste', 'Latn', 'noun', 0, NULL),
  (60, 2, 9, 'kazalište', 'kazalište', 'kazaliste', 'kazaliste', 'Latn', 'noun', 0, NULL),
  (61, 3, 9, 'pozorište', 'pozorište', 'pozoriste', 'pozoriste', 'Latn', 'noun', 0, NULL),
  (62, 4, 9, 'pozorište', 'pozorište', 'pozoriste', 'pozoriste', 'Latn', 'noun', 0, NULL),
  (63, 5, 9, 'gledališče', 'gledališče', 'gledalisce', 'gledalisce', 'Latn', 'noun', 0, NULL),
  (64, 6, 9, 'театар', 'театар', 'театар', 'teatar', 'Cyrl', 'noun', 0, NULL),
  (65, 7, 9, 'theatre', 'theatre', 'theatre', 'theatre', 'Latn', 'noun', 0, NULL),
  (66, 1, 10, 'muzika', 'muzika', 'muzika', 'muzika', 'Latn', 'noun', 0, NULL),
  (67, 2, 10, 'glazba', 'glazba', 'glazba', 'glazba', 'Latn', 'noun', 0, NULL),
  (68, 3, 10, 'muzika', 'muzika', 'muzika', 'muzika', 'Latn', 'noun', 0, NULL),
  (69, 4, 10, 'muzika', 'muzika', 'muzika', 'muzika', 'Latn', 'noun', 0, NULL),
  (70, 5, 10, 'glasba', 'glasba', 'glasba', 'glasba', 'Latn', 'noun', 0, NULL),
  (71, 6, 10, 'музика', 'музика', 'музика', 'muzika', 'Cyrl', 'noun', 0, NULL),
  (72, 7, 10, 'music', 'music', 'music', 'music', 'Latn', 'noun', 0, NULL),
  (73, 1, 11, 'vući za nos', 'vući za nos', 'vuci za nos', 'vuci-za-nos', 'Latn', 'idiom', 1, 'colloquial'),
  (74, 2, 11, 'vući za nos', 'vući za nos', 'vuci za nos', 'vuci-za-nos', 'Latn', 'idiom', 1, 'colloquial'),
  (76, 1, 12, 'bacati bisere pred svinje', 'bacati bisere pred svinje', 'bacati bisere pred svinje', 'bacati-bisere-pred-svinje', 'Latn', 'idiom', 1, 'literary'),
  (77, 2, 12, 'bacati bisere pred svinje', 'bacati bisere pred svinje', 'bacati bisere pred svinje', 'bacati-bisere-pred-svinje', 'Latn', 'idiom', 1, 'literary'),
  (79, 1, 13, 'ko drugome jamu kopa, sam u nju pada', 'ko drugome jamu kopa, sam u nju pada', 'ko drugome jamu kopa sam u nju pada', 'ko-drugome-jamu-kopa', 'Latn', 'idiom', 1, 'literary'),
  (80, 2, 13, 'tko drugome jamu kopa, sam u nju pada', 'tko drugome jamu kopa, sam u nju pada', 'tko drugome jamu kopa sam u nju pada', 'tko-drugome-jamu-kopa', 'Latn', 'idiom', 1, 'literary'),
  (82, 1, 14, 'držati jezik za zubima', 'držati jezik za zubima', 'drzati jezik za zubima', 'drzati-jezik-za-zubima', 'Latn', 'idiom', 1, 'colloquial'),
  (83, 2, 14, 'držati jezik za zubima', 'držati jezik za zubima', 'drzati jezik za zubima', 'drzati-jezik-za-zubima', 'Latn', 'idiom', 1, 'colloquial'),
  (85, 1, 15, 'kupiti mačka u džaku', 'kupiti mačka u džaku', 'kupiti macka u dzaku', 'kupiti-macka-u-dzaku', 'Latn', 'idiom', 1, 'colloquial'),
  (86, 2, 15, 'kupiti mačka u vreći', 'kupiti mačka u vreći', 'kupiti macka u vreci', 'kupiti-macka-u-vreci', 'Latn', 'idiom', 1, 'colloquial'),
  (88, 1, 16, 'bolje vrabac u ruci nego golub na grani', 'bolje vrabac u ruci nego golub na grani', 'bolje vrabac u ruci nego golub na grani', 'bolje-vrabac-u-ruci', 'Latn', 'idiom', 1, 'literary'),
  (89, 2, 16, 'bolje vrabac u ruci nego golub na grani', 'bolje vrabac u ruci nego golub na grani', 'bolje vrabac u ruci nego golub na grani', 'bolje-vrabac-u-ruci', 'Latn', 'idiom', 1, 'literary')
ON DUPLICATE KEY UPDATE display_form = VALUES(display_form);
